### PR TITLE
Bump packages to get audioplayer.

### PR DESCRIPTION
**Pull request by gunnarvelle**
Depends on https://github.com/NDLANO/article-converter/pull/227

Sider med lydavspiller skal fungere med nytt design:
* [Side1](https://ndla-frontend-pr-655.ndla.sh/subject:14/topic:1:126720/topic:1:186343/resource:1:110573?filters=urn:filter:80f10045-2faa-4f6f-be0f-4c7ec9618186)
* [Side2](https://ndla-frontend-pr-655.ndla.sh/subject:14/topic:1:126720/topic:1:186343/resource:1:115811?filters=urn:filter:80f10045-2faa-4f6f-be0f-4c7ec9618186)

### CODE REVIEW

**Comment by haattis** [comment]
Ser at lydklippet i denne [artikkelen](https://ndla-frontend-pr-655.ndla.sh/subject:14/topic:1:126720/topic:1:186343/resource:1:110573?filters=urn:filter:80f10045-2faa-4f6f-be0f-4c7ec9618186) ikke kan spilles i PR-installasjon. Bare i test. Styling mangler også.

**Comment by gunnarvelle** [comment]
Det er fordi article-converter ikkje er deploya i test.

**Comment by gunnarvelle** [comment]
Sjekk feks [denne](https://ndla-frontend-pr-655.ndla.sh/subject:14/topic:1:126720/topic:1:186343/resource:1:115811?filters=urn:filter:80f10045-2faa-4f6f-be0f-4c7ec9618186) @haattis

**Review by haattis — APPROVED** [review]
Det fungerer bra! 💯

**Review by N4G1 — APPROVED** [review]

**Pull request merged**
